#!/usr/bin/env python3
"""Generate sgconfig.yml for ast-grep from all concept rule files.

Usage:
    python generate-sgconfig.py [kordinate-home]

Scans concepts/*/ast-grep.yaml and writes sgconfig.yml to kordinate-home.
Run this after adding/removing concept rule files.
"""

import glob
import os
import sys
from pathlib import Path

def main():
    home = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(os.environ.get("KORDINATE_HOME", os.path.expanduser("~/.kord")))
    concepts_dir = home / "agents" / "augur" / "memory" / "concepts"

    if not concepts_dir.exists():
        print(f"Concepts directory not found: {concepts_dir}", file=sys.stderr)
        sys.exit(1)

    # Find all ast-grep rule files
    rules = sorted(glob.glob(str(concepts_dir / "*/ast-grep.yaml")))

    if not rules:
        print("No ast-grep rules found", file=sys.stderr)
        sys.exit(0)

    # Generate sgconfig.yml
    output = home / "sgconfig.yml"

    lines = [
        "# Auto-generated by generate-sgconfig.py — do not edit manually",
        f"# {len(rules)} rules from {len(rules)} concepts",
        "",
        "ruleDirs:",
    ]

    # ast-grep ruleDirs expects directories containing rule files
    # Group by concept directory
    rule_dirs = sorted(set(str(Path(r).parent.relative_to(home)) for r in rules))
    for d in rule_dirs:
        lines.append(f"  - {d}")

    output.write_text("\n".join(lines) + "\n")
    print(f"Generated {output} with {len(rule_dirs)} rule directories ({len(rules)} rules)", file=sys.stderr)


if __name__ == "__main__":
    main()
