apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitor
resources:
  - manifests/monitor-alloy.yaml
  - manifests/monitor-alloy-config.yaml
  - manifests/monitor-prometheus.yaml
  - manifests/monitor-loki.yaml
  - manifests/monitor-kube-state-metrics.yaml
  - manifests/monitor-node-exporter.yaml
