id: flux-dispatch-ts
language: TypeScript
rule:
  pattern: 'dispatch($ACTION)'
---
id: flux-useDispatch-ts
language: TypeScript
rule:
  pattern: 'useDispatch()'
---
id: flux-createStore-ts
language: TypeScript
rule:
  pattern: 'createStore($$$ARGS)'
---
id: flux-combineReducers-ts
language: TypeScript
rule:
  pattern: 'combineReducers($$$ARGS)'
---
id: flux-connect-ts
language: TypeScript
rule:
  pattern: 'connect($MAP_STATE, $$$REST)'
