#!/bin/bash
# PreToolUse hook: regenerates agent MEMORY.md before spawning a subagent.
# Combines shared memory + instructions + static knowledge into a single
# file that Claude auto-loads from agent-memory/<agent>/.
#
# Only regenerates if source files have changed (hash-based).

INPUT=$(cat)

# Extract agent name from tool_input
AGENT=$(echo "$INPUT" | python3 -c "
import sys, json
d = json.load(sys.stdin)
# subagent_type might be a custom agent name or a built-in type
name = d.get('tool_input', {}).get('subagent_type', '')
print(name.lower())
" 2>/dev/null)

# Only handle our known agents
case "$AGENT" in
  deployer|sauron|designer|scribe) ;;
  *) echo '{}'; exit 0 ;;
esac

# Resolve paths
KORDINATE_HOME="${KORDINATE_HOME:-$(cd "$(dirname "$0")/.." && pwd)}"
AGENT_DIR="$KORDINATE_HOME/agents/$AGENT"
SHARED="$KORDINATE_HOME/agents/shared/MEMORY.md"
STATIC="$AGENT_DIR/memory/static"
INSTRUCTIONS="$AGENT_DIR/instructions"
DYNAMIC="$AGENT_DIR/memory/dynamic"
MEMORY_FILE="$DYNAMIC/MEMORY.md"
HASH_FILE="$DYNAMIC/.hash"

# Ensure dynamic dir exists
mkdir -p "$DYNAMIC"

# Compute hash of source files
CURRENT_HASH=$(find "$SHARED" "$STATIC" "$INSTRUCTIONS" -type f 2>/dev/null | sort | xargs cat 2>/dev/null | md5sum | cut -d' ' -f1)
STORED_HASH=$(cat "$HASH_FILE" 2>/dev/null)

# Skip if unchanged
if [ "$CURRENT_HASH" = "$STORED_HASH" ] && [ -f "$MEMORY_FILE" ]; then
  echo '{}'; exit 0
fi

# Preserve existing Notes section (Claude's auto-managed content)
NOTES=""
if [ -f "$MEMORY_FILE" ]; then
  NOTES=$(sed -n '/^## Notes$/,$ p' "$MEMORY_FILE" | tail -n +2)
fi

# Count total lines in static to decide: inline or index
STATIC_LINES=$(find "$STATIC" -type f -name "*.md" 2>/dev/null | xargs wc -l 2>/dev/null | tail -1 | awk '{print $1}')
STATIC_LINES=${STATIC_LINES:-0}

# Generate MEMORY.md
{
  echo "# Memory"
  echo ""
  echo "<!-- generated by agent-memory.sh — do not edit above Notes -->"
  echo ""

  # Shared memory
  if [ -f "$SHARED" ]; then
    echo "## Shared"
    echo ""
    # Skip the title line
    tail -n +3 "$SHARED"
    echo ""
  fi

  # Instructions (always inline — they're small)
  if [ -d "$INSTRUCTIONS" ] && [ "$(ls -A "$INSTRUCTIONS" 2>/dev/null)" ]; then
    echo "## Instructions"
    echo ""
    for f in "$INSTRUCTIONS"/*.md; do
      [ -f "$f" ] || continue
      cat "$f"
      echo ""
    done
  fi

  # Static knowledge
  if [ -d "$STATIC" ]; then
    if [ "$STATIC_LINES" -le 500 ]; then
      # Small enough — inline everything
      echo "## Knowledge"
      echo ""
      find "$STATIC" -name "*.md" -type f | sort | while read -r f; do
        cat "$f"
        echo ""
      done
    else
      # Too large — generate index
      echo "## Knowledge Index"
      echo ""
      echo "Read on demand from \`memory/static/\`:"
      echo ""
      find "$STATIC" -name "*.md" -type f | sort | while read -r f; do
        name=$(basename "$f" .md)
        relpath="${f#$AGENT_DIR/}"
        echo "- \`$relpath\` — $name"
      done
      echo ""
    fi
  fi

  # Notes section
  echo "## Notes"
  if [ -n "$NOTES" ]; then
    echo "$NOTES"
  else
    echo ""
    echo "(auto-managed by the agent)"
  fi
} > "$MEMORY_FILE"

# Store hash
echo "$CURRENT_HASH" > "$HASH_FILE"

# Allow agent to spawn
echo '{}'
exit 0
