#!/bin/bash
# PreToolUse hook: regenerates agent MEMORY.md before spawning a subagent.
# Combines shared memory + instructions + static knowledge + kord discovery
# into a single file that Claude auto-loads from agent-memory/<agent>/.
#
# Only regenerates if source files have changed (hash-based).

INPUT=$(cat)

# Extract agent name from tool_input
AGENT=$(echo "$INPUT" | python3 -c "
import sys, json
d = json.load(sys.stdin)
# subagent_type might be a custom agent name or a built-in type
name = d.get('tool_input', {}).get('subagent_type', '')
print(name.lower())
" 2>/dev/null)

# Only handle our known agents
case "$AGENT" in
  deployer|sauron|designer|scribe) ;;
  *) echo '{}'; exit 0 ;;
esac

# Resolve paths
KORDINATE_HOME="${KORDINATE_HOME:-$(cd "$(dirname "$0")/.." && pwd)}"
source "$KORDINATE_HOME/lib/cache.sh"

AGENT_DIR="$KORDINATE_HOME/agents/$AGENT"
SHARED="$KORDINATE_HOME/agents/shared/MEMORY.md"
STATIC="$AGENT_DIR/memory/static"
INSTRUCTIONS="$AGENT_DIR/instructions"
DYNAMIC="$AGENT_DIR/memory/dynamic"
KORDS_DIR="$KORDINATE_HOME/agents/root/kords"
MEMORY_FILE="$DYNAMIC/MEMORY.md"
HASH_FILE="$DYNAMIC/.hash"

# Ensure dynamic dir exists
mkdir -p "$DYNAMIC"

# Skip if unchanged (include kords dir in hash check)
if cache_check "$HASH_FILE" "$SHARED" "$STATIC" "$INSTRUCTIONS" "$KORDS_DIR" && [ -f "$MEMORY_FILE" ]; then
  echo '{}'; exit 0
fi

# Preserve existing Notes section (Claude's auto-managed content)
NOTES=""
if [ -f "$MEMORY_FILE" ]; then
  NOTES=$(sed -n '/^## Notes$/,$ p' "$MEMORY_FILE" | tail -n +2)
fi

# Count total lines in static to decide: inline or index
STATIC_LINES=$(find "$STATIC" -type f -name "*.md" 2>/dev/null | xargs wc -l 2>/dev/null | tail -1 | awk '{print $1}')
STATIC_LINES=${STATIC_LINES:-0}

# Generate MEMORY.md
{
  echo "# Memory"
  echo ""
  echo "<!-- generated by agent-memory.sh — do not edit above Notes -->"
  echo ""

  # Shared memory
  if [ -f "$SHARED" ]; then
    echo "## Shared"
    echo ""
    # Skip the title line
    tail -n +3 "$SHARED"
    echo ""
  fi

  # Instructions (always inline — they're small)
  if [ -d "$INSTRUCTIONS" ] && [ "$(ls -A "$INSTRUCTIONS" 2>/dev/null)" ]; then
    echo "## Instructions"
    echo ""
    for f in "$INSTRUCTIONS"/*.md; do
      [ -f "$f" ] || continue
      cat "$f"
      echo ""
    done
  fi

  # Static knowledge
  if [ -d "$STATIC" ]; then
    if [ "$STATIC_LINES" -le 500 ]; then
      # Small enough — inline everything
      echo "## Knowledge"
      echo ""
      find "$STATIC" -name "*.md" -type f | sort | while read -r f; do
        cat "$f"
        echo ""
      done
    else
      # Too large — generate index
      echo "## Knowledge Index"
      echo ""
      echo "Read on demand from \`memory/static/\`:"
      echo ""
      find "$STATIC" -name "*.md" -type f | sort | while read -r f; do
        name=$(basename "$f" .md)
        relpath="${f#$AGENT_DIR/}"
        echo "- \`$relpath\` — $name"
      done
      echo ""
    fi
  fi

  # Kord discovery — find kords where this agent is requester or provider
  if [ -d "$KORDS_DIR" ]; then
    requester_kords=()
    provider_kords=()
    for kord_dir in "$KORDS_DIR"/*/; do
      [ -d "$kord_dir" ] || continue
      kord_md="$kord_dir/kord.md"
      [ -f "$kord_md" ] || continue
      kord_name=$(basename "$kord_dir")

      # Check provider
      provider=$(sed -n '/^## Provider$/,/^##/{/^## Provider$/d;/^##/d;/^$/d;p;}' "$kord_md" | head -1 | tr -d '[:space:]')
      if [ "$provider" = "$AGENT" ]; then
        provider_kords+=("$kord_name")
      fi

      # Check requester
      requester_line=$(sed -n '/^## Requester$/,/^##/{/^## Requester$/d;/^##/d;/^$/d;p;}' "$kord_md" | head -1)
      if [[ "$requester_line" == *"any"* ]] || [[ "$requester_line" == *"$AGENT"* ]]; then
        requester_kords+=("$kord_name")
      fi
    done

    if [ ${#requester_kords[@]} -gt 0 ] || [ ${#provider_kords[@]} -gt 0 ]; then
      echo "## Kords"
      echo ""
      if [ ${#provider_kords[@]} -gt 0 ]; then
        echo "You are **provider** for: ${provider_kords[*]}"
        echo ""
      fi
      if [ ${#requester_kords[@]} -gt 0 ]; then
        echo "You can **request** via: ${requester_kords[*]}"
        echo ""
      fi
      echo "Use \`/consult <kord-or-agent> \"<question>\"\` to invoke."
      echo ""
    fi
  fi

  # Notes section
  echo "## Notes"
  if [ -n "$NOTES" ]; then
    echo "$NOTES"
  else
    echo ""
    echo "(auto-managed by the agent)"
  fi
} > "$MEMORY_FILE"

# Store hash (include kords dir)
cache_store "$HASH_FILE" "$SHARED" "$STATIC" "$INSTRUCTIONS" "$KORDS_DIR"

# Allow agent to spawn
echo '{}'
exit 0
