apiVersion: v1
kind: Namespace
metadata:
  name: monitor
  labels:
    app: monitoring
    tier: monitor
---
apiVersion: v1
kind: Namespace
metadata:
  name: master
  labels:
    app: monitoring
    tier: master
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    app: kord-infra
---
apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    app: kord-infra
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    app: kord-infra
